window.TRACKER_DATA = {
    "source":  "Weekly_DD_POS_Tracker_Click_Toggle_Targets (1).xlsx",
    "updated":  "2026-05-25 11:30",
    "overview":  {
                     "totalDD":  326690.47,
                     "totalPOS":  20411.03,
                     "totalRevenue":  347101.5,
                     "avgPOSPercent":  6.2
                 },
    "rolling":  [
                    {
                        "weekEnding":  "2026-04-09",
                        "club":  "Wetherill Park",
                        "ddActual":  18764.98,
                        "ddTarget":  19099.75,
                        "ddGap":  -334.77,
                        "posActual":  1056.68,
                        "posTarget":  1527.98,
                        "posPercent":  5.6,
                        "targetPercent":  8,
                        "status":  "RED"
                    },
                    {
                        "weekEnding":  "2026-04-09",
                        "club":  "Bankstown",
                        "ddActual":  23345.35,
                        "ddTarget":  23186.4,
                        "ddGap":  158.95,
                        "posActual":  2624.23,
                        "posTarget":  1921.75,
                        "posPercent":  11.2,
                        "targetPercent":  8.3,
                        "status":  "GREEN"
                    },
                    {
                        "weekEnding":  "2026-04-09",
                        "club":  "580G",
                        "ddActual":  14167.01,
                        "ddTarget":  14994.63,
                        "ddGap":  -827.62,
                        "posActual":  1230.69,
                        "posTarget":  1199.57,
                        "posPercent":  8.7,
                        "targetPercent":  8,
                        "status":  "RED"
                    },
                    {
                        "weekEnding":  "2026-04-09",
                        "club":  "Woolooware",
                        "ddActual":  12734.27,
                        "ddTarget":  13856.86,
                        "ddGap":  -1122.59,
                        "posActual":  521.14,
                        "posTarget":  1108.55,
                        "posPercent":  4.1,
                        "targetPercent":  8,
                        "status":  "RED"
                    },
                    {
                        "weekEnding":  "2026-04-16",
                        "club":  "Wetherill Park",
                        "ddActual":  17815.35,
                        "ddTarget":  19099.75,
                        "ddGap":  -1284.4,
                        "posActual":  1124.91,
                        "posTarget":  1527.98,
                        "posPercent":  6.3,
                        "targetPercent":  8,
                        "status":  "RED"
                    },
                    {
                        "weekEnding":  "2026-04-16",
                        "club":  "Bankstown",
                        "ddActual":  21426.23,
                        "ddTarget":  23186.4,
                        "ddGap":  -1760.17,
                        "posActual":  1541.91,
                        "posTarget":  1921.75,
                        "posPercent":  7.2,
                        "targetPercent":  8.3,
                        "status":  "RED"
                    },
                    {
                        "weekEnding":  "2026-04-16",
                        "club":  "580G",
                        "ddActual":  13713.36,
                        "ddTarget":  14994.63,
                        "ddGap":  -1281.27,
                        "posActual":  736.85,
                        "posTarget":  1199.57,
                        "posPercent":  5.4,
                        "targetPercent":  8,
                        "status":  "RED"
                    },
                    {
                        "weekEnding":  "2026-04-16",
                        "club":  "Woolooware",
                        "ddActual":  13090.34,
                        "ddTarget":  13856.86,
                        "ddGap":  -766.52,
                        "posActual":  187.97,
                        "posTarget":  1108.55,
                        "posPercent":  1.4,
                        "targetPercent":  8,
                        "status":  "RED"
                    },
                    {
                        "weekEnding":  "2026-04-23",
                        "club":  "Wetherill Park",
                        "ddActual":  17909.8,
                        "ddTarget":  19099.75,
                        "ddGap":  -1189.95,
                        "posActual":  654.41,
                        "posTarget":  1527.98,
                        "posPercent":  3.7,
                        "targetPercent":  8,
                        "status":  "RED"
                    },
                    {
                        "weekEnding":  "2026-04-23",
                        "club":  "Bankstown",
                        "ddActual":  21410.39,
                        "ddTarget":  23186.4,
                        "ddGap":  -1776.01,
                        "posActual":  1598.27,
                        "posTarget":  1921.75,
                        "posPercent":  7.5,
                        "targetPercent":  8.3,
                        "status":  "RED"
                    },
                    {
                        "weekEnding":  "2026-04-23",
                        "club":  "580G",
                        "ddActual":  13861.36,
                        "ddTarget":  14994.63,
                        "ddGap":  -1133.27,
                        "posActual":  1015.22,
                        "posTarget":  1199.57,
                        "posPercent":  7.3,
                        "targetPercent":  8,
                        "status":  "RED"
                    },
                    {
                        "weekEnding":  "2026-04-23",
                        "club":  "Woolooware",
                        "ddActual":  12923.55,
                        "ddTarget":  13856.86,
                        "ddGap":  -933.31,
                        "posActual":  401.59,
                        "posTarget":  1108.55,
                        "posPercent":  3.1,
                        "targetPercent":  8,
                        "status":  "RED"
                    },
                    {
                        "weekEnding":  "2026-04-30",
                        "club":  "Wetherill Park",
                        "ddActual":  16249.7,
                        "ddTarget":  19099.75,
                        "ddGap":  -2850.05,
                        "posActual":  1093.68,
                        "posTarget":  1527.98,
                        "posPercent":  6.7,
                        "targetPercent":  8,
                        "status":  "RED"
                    },
                    {
                        "weekEnding":  "2026-04-30",
                        "club":  "Bankstown",
                        "ddActual":  19693.57,
                        "ddTarget":  23186.4,
                        "ddGap":  -3492.83,
                        "posActual":  1427.95,
                        "posTarget":  1921.75,
                        "posPercent":  7.3,
                        "targetPercent":  8.3,
                        "status":  "RED"
                    },
                    {
                        "weekEnding":  "2026-04-30",
                        "club":  "580G",
                        "ddActual":  13793.94,
                        "ddTarget":  14994.63,
                        "ddGap":  -1200.69,
                        "posActual":  816.43,
                        "posTarget":  1199.57,
                        "posPercent":  5.9,
                        "targetPercent":  8,
                        "status":  "RED"
                    },
                    {
                        "weekEnding":  "2026-04-30",
                        "club":  "Woolooware",
                        "ddActual":  12573.53,
                        "ddTarget":  13856.86,
                        "ddGap":  -1283.33,
                        "posActual":  293.72,
                        "posTarget":  1108.55,
                        "posPercent":  2.3,
                        "targetPercent":  8,
                        "status":  "RED"
                    },
                    {
                        "weekEnding":  "2026-05-07",
                        "club":  "Wetherill Park",
                        "ddActual":  17064.75,
                        "ddTarget":  19099.75,
                        "ddGap":  -2035,
                        "posActual":  1193.14,
                        "posTarget":  1527.98,
                        "posPercent":  7,
                        "targetPercent":  8,
                        "status":  "RED"
                    },
                    {
                        "weekEnding":  "2026-05-07",
                        "club":  "Bankstown",
                        "ddActual":  20225.85,
                        "ddTarget":  23186.4,
                        "ddGap":  -2960.55,
                        "posActual":  1996.68,
                        "posTarget":  1921.75,
                        "posPercent":  9.9,
                        "targetPercent":  8.3,
                        "status":  "RED"
                    },
                    {
                        "weekEnding":  "2026-05-07",
                        "club":  "580G",
                        "ddActual":  13304.3,
                        "ddTarget":  14994.63,
                        "ddGap":  -1690.33,
                        "posActual":  606.81,
                        "posTarget":  1199.57,
                        "posPercent":  4.6,
                        "targetPercent":  8,
                        "status":  "RED"
                    },
                    {
                        "weekEnding":  "2026-05-07",
                        "club":  "Woolooware",
                        "ddActual":  12622.84,
                        "ddTarget":  13856.86,
                        "ddGap":  -1234.02,
                        "posActual":  288.75,
                        "posTarget":  1108.55,
                        "posPercent":  2.3,
                        "targetPercent":  8,
                        "status":  "RED"
                    },
                    {
                        "weekEnding":  "2026-05-14",
                        "club":  "Wetherill Park",
                        "ddActual":  null,
                        "ddTarget":  19099.75,
                        "ddGap":  -19099.75,
                        "posActual":  null,
                        "posTarget":  1527.98,
                        "posPercent":  null,
                        "targetPercent":  8,
                        "status":  ""
                    },
                    {
                        "weekEnding":  "2026-05-14",
                        "club":  "Bankstown",
                        "ddActual":  null,
                        "ddTarget":  23186.4,
                        "ddGap":  -23186.4,
                        "posActual":  null,
                        "posTarget":  1921.75,
                        "posPercent":  null,
                        "targetPercent":  8.3,
                        "status":  ""
                    },
                    {
                        "weekEnding":  "2026-05-14",
                        "club":  "580G",
                        "ddActual":  null,
                        "ddTarget":  14994.63,
                        "ddGap":  -14994.63,
                        "posActual":  null,
                        "posTarget":  1199.57,
                        "posPercent":  null,
                        "targetPercent":  8,
                        "status":  ""
                    },
                    {
                        "weekEnding":  "2026-05-14",
                        "club":  "Woolooware",
                        "ddActual":  null,
                        "ddTarget":  13856.86,
                        "ddGap":  -13856.86,
                        "posActual":  null,
                        "posTarget":  1108.55,
                        "posPercent":  null,
                        "targetPercent":  8,
                        "status":  ""
                    },
                    {
                        "weekEnding":  "2026-05-21",
                        "club":  "Wetherill Park",
                        "ddActual":  null,
                        "ddTarget":  19099.75,
                        "ddGap":  -19099.75,
                        "posActual":  null,
                        "posTarget":  1527.98,
                        "posPercent":  null,
                        "targetPercent":  8,
                        "status":  ""
                    },
                    {
                        "weekEnding":  "2026-05-21",
                        "club":  "Bankstown",
                        "ddActual":  null,
                        "ddTarget":  23186.4,
                        "ddGap":  -23186.4,
                        "posActual":  null,
                        "posTarget":  1921.75,
                        "posPercent":  null,
                        "targetPercent":  8.3,
                        "status":  ""
                    },
                    {
                        "weekEnding":  "2026-05-21",
                        "club":  "580G",
                        "ddActual":  null,
                        "ddTarget":  14994.63,
                        "ddGap":  -14994.63,
                        "posActual":  null,
                        "posTarget":  1199.57,
                        "posPercent":  null,
                        "targetPercent":  8,
                        "status":  ""
                    },
                    {
                        "weekEnding":  "2026-05-21",
                        "club":  "Woolooware",
                        "ddActual":  null,
                        "ddTarget":  13856.86,
                        "ddGap":  -13856.86,
                        "posActual":  null,
                        "posTarget":  1108.55,
                        "posPercent":  null,
                        "targetPercent":  8,
                        "status":  ""
                    },
                    {
                        "weekEnding":  "2026-05-28",
                        "club":  "Wetherill Park",
                        "ddActual":  null,
                        "ddTarget":  19099.75,
                        "ddGap":  -19099.75,
                        "posActual":  null,
                        "posTarget":  1527.98,
                        "posPercent":  null,
                        "targetPercent":  8,
                        "status":  ""
                    },
                    {
                        "weekEnding":  "2026-05-28",
                        "club":  "Bankstown",
                        "ddActual":  null,
                        "ddTarget":  23186.4,
                        "ddGap":  -23186.4,
                        "posActual":  null,
                        "posTarget":  1921.75,
                        "posPercent":  null,
                        "targetPercent":  8.3,
                        "status":  ""
                    },
                    {
                        "weekEnding":  "2026-05-28",
                        "club":  "580G",
                        "ddActual":  null,
                        "ddTarget":  14994.63,
                        "ddGap":  -14994.63,
                        "posActual":  null,
                        "posTarget":  1199.57,
                        "posPercent":  null,
                        "targetPercent":  8,
                        "status":  ""
                    },
                    {
                        "weekEnding":  "2026-05-28",
                        "club":  "Woolooware",
                        "ddActual":  null,
                        "ddTarget":  13856.86,
                        "ddGap":  -13856.86,
                        "posActual":  null,
                        "posTarget":  1108.55,
                        "posPercent":  null,
                        "targetPercent":  8,
                        "status":  ""
                    },
                    {
                        "weekEnding":  "2026-06-04",
                        "club":  "Wetherill Park",
                        "ddActual":  null,
                        "ddTarget":  19099.75,
                        "ddGap":  -19099.75,
                        "posActual":  null,
                        "posTarget":  1527.98,
                        "posPercent":  null,
                        "targetPercent":  8,
                        "status":  ""
                    },
                    {
                        "weekEnding":  "2026-06-04",
                        "club":  "Bankstown",
                        "ddActual":  null,
                        "ddTarget":  23186.4,
                        "ddGap":  -23186.4,
                        "posActual":  null,
                        "posTarget":  1921.75,
                        "posPercent":  null,
                        "targetPercent":  8.3,
                        "status":  ""
                    },
                    {
                        "weekEnding":  "2026-06-04",
                        "club":  "580G",
                        "ddActual":  null,
                        "ddTarget":  14994.63,
                        "ddGap":  -14994.63,
                        "posActual":  null,
                        "posTarget":  1199.57,
                        "posPercent":  null,
                        "targetPercent":  8,
                        "status":  ""
                    },
                    {
                        "weekEnding":  "2026-06-04",
                        "club":  "Woolooware",
                        "ddActual":  null,
                        "ddTarget":  13856.86,
                        "ddGap":  -13856.86,
                        "posActual":  null,
                        "posTarget":  1108.55,
                        "posPercent":  null,
                        "targetPercent":  8,
                        "status":  ""
                    },
                    {
                        "weekEnding":  "2026-06-11",
                        "club":  "Wetherill Park",
                        "ddActual":  null,
                        "ddTarget":  19099.75,
                        "ddGap":  -19099.75,
                        "posActual":  null,
                        "posTarget":  1527.98,
                        "posPercent":  null,
                        "targetPercent":  8,
                        "status":  ""
                    },
                    {
                        "weekEnding":  "2026-06-11",
                        "club":  "Bankstown",
                        "ddActual":  null,
                        "ddTarget":  23186.4,
                        "ddGap":  -23186.4,
                        "posActual":  null,
                        "posTarget":  1921.75,
                        "posPercent":  null,
                        "targetPercent":  8.3,
                        "status":  ""
                    },
                    {
                        "weekEnding":  "2026-06-11",
                        "club":  "580G",
                        "ddActual":  null,
                        "ddTarget":  14994.63,
                        "ddGap":  -14994.63,
                        "posActual":  null,
                        "posTarget":  1199.57,
                        "posPercent":  null,
                        "targetPercent":  8,
                        "status":  ""
                    },
                    {
                        "weekEnding":  "2026-06-11",
                        "club":  "Woolooware",
                        "ddActual":  null,
                        "ddTarget":  13856.86,
                        "ddGap":  -13856.86,
                        "posActual":  null,
                        "posTarget":  1108.55,
                        "posPercent":  null,
                        "targetPercent":  8,
                        "status":  ""
                    },
                    {
                        "weekEnding":  "2026-06-18",
                        "club":  "Wetherill Park",
                        "ddActual":  null,
                        "ddTarget":  19099.75,
                        "ddGap":  -19099.75,
                        "posActual":  null,
                        "posTarget":  1527.98,
                        "posPercent":  null,
                        "targetPercent":  8,
                        "status":  ""
                    },
                    {
                        "weekEnding":  "2026-06-18",
                        "club":  "Bankstown",
                        "ddActual":  null,
                        "ddTarget":  23186.4,
                        "ddGap":  -23186.4,
                        "posActual":  null,
                        "posTarget":  1921.75,
                        "posPercent":  null,
                        "targetPercent":  8.3,
                        "status":  ""
                    },
                    {
                        "weekEnding":  "2026-06-18",
                        "club":  "580G",
                        "ddActual":  null,
                        "ddTarget":  14994.63,
                        "ddGap":  -14994.63,
                        "posActual":  null,
                        "posTarget":  1199.57,
                        "posPercent":  null,
                        "targetPercent":  8,
                        "status":  ""
                    },
                    {
                        "weekEnding":  "2026-06-18",
                        "club":  "Woolooware",
                        "ddActual":  null,
                        "ddTarget":  13856.86,
                        "ddGap":  -13856.86,
                        "posActual":  null,
                        "posTarget":  1108.55,
                        "posPercent":  null,
                        "targetPercent":  8,
                        "status":  ""
                    },
                    {
                        "weekEnding":  "2026-06-25",
                        "club":  "Wetherill Park",
                        "ddActual":  null,
                        "ddTarget":  19099.75,
                        "ddGap":  -19099.75,
                        "posActual":  null,
                        "posTarget":  1527.98,
                        "posPercent":  null,
                        "targetPercent":  8,
                        "status":  ""
                    },
                    {
                        "weekEnding":  "2026-06-25",
                        "club":  "Bankstown",
                        "ddActual":  null,
                        "ddTarget":  23186.4,
                        "ddGap":  -23186.4,
                        "posActual":  null,
                        "posTarget":  1921.75,
                        "posPercent":  null,
                        "targetPercent":  8.3,
                        "status":  ""
                    },
                    {
                        "weekEnding":  "2026-06-25",
                        "club":  "580G",
                        "ddActual":  null,
                        "ddTarget":  14994.63,
                        "ddGap":  -14994.63,
                        "posActual":  null,
                        "posTarget":  1199.57,
                        "posPercent":  null,
                        "targetPercent":  8,
                        "status":  ""
                    },
                    {
                        "weekEnding":  "2026-06-25",
                        "club":  "Woolooware",
                        "ddActual":  null,
                        "ddTarget":  13856.86,
                        "ddGap":  -13856.86,
                        "posActual":  null,
                        "posTarget":  1108.55,
                        "posPercent":  null,
                        "targetPercent":  8,
                        "status":  ""
                    }
                ],
    "summary":  [
                    {
                        "club":  "Wetherill Park",
                        "totalDD":  87804.58,
                        "totalPOS":  5122.82,
                        "posPercent":  5.8,
                        "ddGap":  -141392.47,
                        "redWeeks":  5,
                        "greenWeeks":  0
                    },
                    {
                        "club":  "Bankstown",
                        "totalDD":  106101.39,
                        "totalPOS":  9189.04,
                        "posPercent":  8.7,
                        "ddGap":  -172135.36,
                        "redWeeks":  4,
                        "greenWeeks":  1
                    },
                    {
                        "club":  "580G",
                        "totalDD":  68839.97,
                        "totalPOS":  4406,
                        "posPercent":  6.4,
                        "ddGap":  -111095.6,
                        "redWeeks":  5,
                        "greenWeeks":  0
                    },
                    {
                        "club":  "Woolooware",
                        "totalDD":  63944.53,
                        "totalPOS":  1693.17,
                        "posPercent":  2.6,
                        "ddGap":  -102337.75,
                        "redWeeks":  5,
                        "greenWeeks":  0
                    }
                ],
    "latest":  [
                   {
                       "club":  "Wetherill Park",
                       "week":  "Week 1",
                       "ddActual":  16249,
                       "ddTarget":  18500,
                       "ddGap":  -2251,
                       "posActual":  1093,
                       "posTarget":  1480,
                       "posPercent":  6.7,
                       "targetPercent":  8,
                       "status":  "RED"
                   },
                   {
                       "club":  "Bankstown",
                       "week":  "Week 1",
                       "ddActual":  19693,
                       "ddTarget":  22000,
                       "ddGap":  -2307,
                       "posActual":  1427,
                       "posTarget":  1760,
                       "posPercent":  7.2,
                       "targetPercent":  8,
                       "status":  "RED"
                   },
                   {
                       "club":  "580G",
                       "week":  "Week 1",
                       "ddActual":  13793,
                       "ddTarget":  14000,
                       "ddGap":  -207,
                       "posActual":  816,
                       "posTarget":  1120,
                       "posPercent":  5.9,
                       "targetPercent":  8,
                       "status":  "RED"
                   },
                   {
                       "club":  "Woolooware",
                       "week":  "Week 1",
                       "ddActual":  12573,
                       "ddTarget":  13500,
                       "ddGap":  -927,
                       "posActual":  293,
                       "posTarget":  1080,
                       "posPercent":  2.3,
                       "targetPercent":  8,
                       "status":  "RED"
                   },
                   {
                       "club":  "Wetherill Park",
                       "week":  "Week 1",
                       "ddActual":  16249,
                       "ddTarget":  18500,
                       "ddGap":  -2251,
                       "posActual":  1093,
                       "posTarget":  1480,
                       "posPercent":  6.7,
                       "targetPercent":  8,
                       "status":  "RED"
                   },
                   {
                       "club":  "Bankstown",
                       "week":  "Week 1",
                       "ddActual":  19693,
                       "ddTarget":  22000,
                       "ddGap":  -2307,
                       "posActual":  1427,
                       "posTarget":  1760,
                       "posPercent":  7.2,
                       "targetPercent":  8,
                       "status":  "RED"
                   },
                   {
                       "club":  "580G",
                       "week":  "Week 1",
                       "ddActual":  13793,
                       "ddTarget":  14000,
                       "ddGap":  -207,
                       "posActual":  816,
                       "posTarget":  1120,
                       "posPercent":  5.9,
                       "targetPercent":  8,
                       "status":  "RED"
                   },
                   {
                       "club":  "Woolooware",
                       "week":  "Week 1",
                       "ddActual":  12573,
                       "ddTarget":  13500,
                       "ddGap":  -927,
                       "posActual":  293,
                       "posTarget":  1080,
                       "posPercent":  2.3,
                       "targetPercent":  8,
                       "status":  "RED"
                   }
               ],
    "targets":  [
                    {
                        "club":  "Wetherill Park",
                        "ddTarget":  20000,
                        "posTargetPercent":  8,
                        "posTargetDollars":  1600
                    },
                    {
                        "club":  "Bankstown",
                        "ddTarget":  22000,
                        "posTargetPercent":  8,
                        "posTargetDollars":  1760
                    },
                    {
                        "club":  "580G",
                        "ddTarget":  18000,
                        "posTargetPercent":  8,
                        "posTargetDollars":  1440
                    },
                    {
                        "club":  "Woolooware",
                        "ddTarget":  18000,
                        "posTargetPercent":  8,
                        "posTargetDollars":  1440
                    }
                ],
    "dynamicTargets":  [
                           {
                               "club":  "Wetherill Park",
                               "rollingAvgDD":  17684.96,
                               "realisticDDTarget":  19099.75,
                               "stretchDDTarget":  19807.15,
                               "rollingAvgPOSPercent":  5.6,
                               "realisticPOSPercentTarget":  8,
                               "stretchPOSPercentTarget":  13.6,
                               "realisticPOSDollars":  1527.98,
                               "stretchPOSDollars":  2690.3,
                               "targetNote":  "POS below floor - focus upsell"
                           },
                           {
                               "club":  "Bankstown",
                               "rollingAvgDD":  21468.88,
                               "realisticDDTarget":  23186.4,
                               "stretchDDTarget":  24045.15,
                               "rollingAvgPOSPercent":  8.3,
                               "realisticPOSPercentTarget":  8.3,
                               "stretchPOSPercentTarget":  16.3,
                               "realisticPOSDollars":  1921.75,
                               "stretchPOSDollars":  3916.54,
                               "targetNote":  "On track"
                           },
                           {
                               "club":  "580G",
                               "rollingAvgDD":  13883.92,
                               "realisticDDTarget":  14994.63,
                               "stretchDDTarget":  15549.99,
                               "rollingAvgPOSPercent":  6.8,
                               "realisticPOSPercentTarget":  8,
                               "stretchPOSPercentTarget":  14.8,
                               "realisticPOSDollars":  1199.57,
                               "stretchPOSDollars":  2305.41,
                               "targetNote":  "POS below floor - focus upsell"
                           },
                           {
                               "club":  "Woolooware",
                               "rollingAvgDD":  12830.42,
                               "realisticDDTarget":  13856.86,
                               "stretchDDTarget":  14370.07,
                               "rollingAvgPOSPercent":  2.7,
                               "realisticPOSPercentTarget":  8,
                               "stretchPOSPercentTarget":  10.7,
                               "realisticPOSDollars":  1108.55,
                               "stretchPOSDollars":  1543.77,
                               "targetNote":  "POS below floor - focus upsell"
                           }
                       ]
}
;

